- name: "HIGH | V-1093 | AUDIT | Anonymous enumeration of shares will be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v RestrictAnonymous
  register: anon_shares_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous enumeration of shares will be restricted."
  win_regedit: 
    key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
    value: RestrictAnonymous
    data: 1
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg
  register: anon_registry_access_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1152

# NOTE: V-1152 is shared between all OS's, but Backup Operators data for 2k12 is 'Read (This key only)' and for 2k8 is 'Special'.
- name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
  win_regedit: 
    key: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg'
    value: "{{ item.value }}"
    data: "{{ item.data }}"
  with_items: 
    - { value: 'Administrators', data: 'Full' }
    - { value: 'Backup Operators', data: 'Special' }
    - { value: 'LOCAL SERVICE', data: 'Read' }
  tags:
      - cat1
      - high
      - patch
      - V-1152

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option will be set to prevent automatic logon to the system."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SecurityLevel
  register: security_level_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option will be set to prevent automatic logon to the system."
  win_regedit: 
    key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
    value: SecurityLevel
    data: 0
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1159

- name: "HIGH | V-2374 | AUDIT | Autoplay will be disabled for all drives."
  win_command: reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer /v NoDriveTypeAutorun
  register: disable_autoplay_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | Autoplay will be disabled for all drives."
  win_regedit: 
    key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer'
    value: NoDriveTypeAutorun
    data: 0x000000ff
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-2374

