- name: "HIGH | V-1093 | AUDIT | Anonymous enumeration of shares will be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v RestrictAnonymous
  register: anon_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_shares_audit.stderr and anon_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous enumeration of shares will be restricted."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: RestrictAnonymous
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg
  register: anon_registry_access_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_registry_access_audit.stderr and anon_registry_access_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1152

# NOTE: V-1152 is shared between all OS's, but Backup Operators data for 2k12 is 'Read (This key only)' and for 2k8 is 'Special'.
- name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
  win_regedit: 
      key: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg'
      value: "{{ item.value }}"
      data: "{{ item.data }}"
  
  with_items: 
      - value: 'Administrators'
        data: 'Full'
      - value: 'Backup Operators'
        data: 'Special'
      - value: 'LOCAL SERVICE'
        data: 'Read' 
  tags:
      - cat1
      - high
      - patch
      - V-1152

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option will be set to prevent automatic logon to the system."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SecurityLevel
  register: security_level_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in security_level_audit.stderr and security_level_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option will be set to prevent automatic logon to the system."
  win_regedit: 
      key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
      value: SecurityLevel
      data: 0
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1159

- name: "HIGH | V-2374 | AUDIT | Autoplay will be disabled for all drives."
  win_command: reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer /v NoDriveTypeAutorun
  register: disable_autoplay_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_autoplay_audit.stderr and disable_autoplay_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | Autoplay will be disabled for all drives."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer'
      value: NoDriveTypeAutorun
      data: 0x000000ff
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-2374

- name: "HIGH | V-3340 | AUDIT | Network shares that can be accessed anonymously will not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v NullSessionShares
  register: null_session_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in null_session_shares_audit.stderr and null_session_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3340

- name: "HIGH | V-3340 | PATCH | Network shares that can be accessed anonymously will not be allowed."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
      value: NullSessionShares
      data: ''
      datatype: multistring
  tags:
      - cat1
      - high
      - patch
      - V-3340

- name: "HIGH | V-3379 | AUDIT | The system will be configured to prevent the storage of the LAN Manager hash of passwords."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v NoLMHash
  register: no_LM_has_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in no_LM_has_audit.stderr and no_LM_has_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3379

- name: "HIGH | V-3379 | PATCH | The system will be configured to prevent the storage of the LAN Manager hash of passwords."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: NoLMHash
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-3379

