- name: "HIGH | V-1073 | AUDIT | Systems must be maintained at a supported service pack level."
  win_command: wmic os get Caption, Version, CSDVersion, BuildNumber
  register: supported_pack_level_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in supported_pack_level_audit.stderr and supported_pack_level_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1073

- name: "HIGH | V-1074 | AUDIT | An approved DoD antivirus program must be installed and used."
  win_command: reg query HKLM\Software\McAfee\DesktopProtection /v szProductVer
  register: mcafee_approved_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in mcafee_approved_audit.stderr and mcafee_approved_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1074

- name: "HIGH | V-1081 | AUDIT | Local volumes must be formatted using NTFS."
  win_shell: Get-WMIObject -Class Win32_Volume | Select DriveLetter,FileSystem
  register: local_volume_format_aduit
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - high
      - audit
      - V-1081

- name: "HIGH | V-1093 | AUDIT | Anonymous enumeration of shares will be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v RestrictAnonymous
  register: anon_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_shares_audit.stderr and anon_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous enumeration of shares will be restricted."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: RestrictAnonymous
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1127 | AUDIT | Only administrators responsible for the system must have Administrator rights on the system."
  win_command: net localgroup Administrators
  register: administrators_audit
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - high
      - audit
      - V-1127

# - name: "HIGH | V-1127 | PATCH | Only administrators responsible for the system must have Administrator rights on the system."
#   win_command: true
#   tags:
#       - cat1
#       - high
#       - patch
#       - V-1127

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_shell: Get-Acl -PATH 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg' | Format-List
  register: anon_registry_access_audit
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - high
      - audit
      - V-1152

# NOTE: V-1152 is shared between all OS's, but Backup Operators data for 2k12 is 'Read (This key only)' and for 2k8 is 'Special'.
# Need script
# - name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
#   script: v1152.ps1
#   changed_when: no
#   tags:
#        - cat1
#        - high
#        - patch
#        - V-1152

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option will be set to prevent automatic logon to the system."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SecurityLevel
  register: security_level_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in security_level_audit.stderr and security_level_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option will be set to prevent automatic logon to the system."
  win_regedit: 
      key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
      value: SecurityLevel
      data: 0
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1159

- name: "HIGH | V-2374 | AUDIT | Autoplay will be disabled for all drives."
  win_command: reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer /v NoDriveTypeAutorun
  register: disable_autoplay_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_autoplay_audit.stderr and disable_autoplay_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | Autoplay will be disabled for all drives."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer'
      value: NoDriveTypeAutorun
      data: 0x000000ff
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-2374

- name: "HIGH | V-3340 | AUDIT | Network shares that can be accessed anonymously will not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v NullSessionShares
  register: null_session_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in null_session_shares_audit.stderr and null_session_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3340

- name: "HIGH | V-3340 | PATCH | Network shares that can be accessed anonymously will not be allowed."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
      value: NullSessionShares
      data: ''
      datatype: multistring
  tags:
      - cat1
      - high
      - patch
      - V-3340

- name: "HIGH | V-3379 | AUDIT | The system will be configured to prevent the storage of the LAN Manager hash of passwords."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v NoLMHash
  register: no_LM_has_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in no_LM_has_audit.stderr and no_LM_has_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3379

- name: "HIGH | V-3379 | PATCH | The system will be configured to prevent the storage of the LAN Manager hash of passwords."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: NoLMHash
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-3379

- name: "HIGH | V-6834 | AUDIT | Anonymous access to Named Pipes and Shares must be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters\ /v RestrictNullSessAccess
  register: anon_access_pipes_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_access_pipes_shares_audit.stderr and anon_access_pipes_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-6834

- name: "HIGH | V-6834 | PATCH | Anonymous access to Named Pipes and Shares must be restricted."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters\'
      value: RestrictNullSessAccess
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-6834

- name: "HIGH | V-7002 | AUDIT | DoD information system access will require the use of a password."
  win_shell: (([ADSI]"WinNT://$env:computername").Children | Where-Object {$_.schemaclassname -eq 'user' -and $_.PasswordRequired -eq $False}).Name
  register: no_password_users_audit
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - high
      - audit
      - V-7002

# - name: "HIGH | V-7002 | PATCH | DoD information system access will require the use of a password."
#   win_command: Net users {{ item }} /passwordreq:yes
#   with_items: 
#       - "{{ no_password_users_audit.stdout_lines }}"
#   tags:
#       - cat1
#       - high
#       - patch
#       - V-7002

- name: "HIGH | V-22692 | AUDIT | The default Autorun behavior must be configured to prevent Autorun commands."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\ /v NoAutorun
  register: autorun_prevent_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in autorun_prevent_audit.stderr and autorun_prevent_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-22692

- name: "HIGH | V-22692 | PATCH | The default Autorun behavior must be configured to prevent Autorun commands."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\'
      value: NoAutorun
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-22692

- name: "HIGH | V-26070 | AUDIT | Standard user accounts must only have Read permissions to the Winlogon registry key."
  win_shell: Get-Acl -PATH 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' | Format-List
  register: standard_user_read_audit
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - high
      - audit
      - V-26070

- name: "HIGH | V-26070 | PATCH | Standard user accounts must only have Read permissions to the Winlogon registry key."
  script: v26070.ps1
  when: >
    'TrustedInstaller Allow  FullControl' not in standard_user_read_audit.stdout or 'SYSTEM Allow  FullControl' not in standard_user_read_audit.stdout or 
    'Administrators Allow  FullControl' not in standard_user_read_audit.stdout or 'Users Allow  ReadKey' not in standard_user_read_audit.stdout
  tags:
      - cat1
      - high
      - patch
      - V-26070

- name: "HIGH | V-26283 | AUDIT | Anonymous enumeration of SAM accounts must not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa\ /v RestrictAnonymousSAM
  register: anonymous_enum_sam_audit
  check_mode: no
  changed_when: no
  failed_when: "anonymous_enum_sam_audit.stderr and reg_not_found not in anonymous_enum_sam_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-26283

- name: "HIGH | V-26283 | PATCH | Anonymous enumeration of SAM accounts must not be allowed."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa\'
      value: RestrictAnonymousSAM
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-26283

- name: "HIGH | V-34974 | AUDIT | The Windows Installer Always install with elevated privileges option must be disabled."
  win_command: reg query HKLM\Software\Policies\Microsoft\Windows\Installer\ /v AlwaysInstallElevated
  register: install_elevated_disabled_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in install_elevated_disabled_audit.stderr and install_elevated_disabled_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-34974

- name: "HIGH | V-34974 | PATCH | The Windows Installer Always install with elevated privileges option must be disabled."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Installer\'
      value: AlwaysInstallElevated
      data: 0
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-34974

