- name: "MEDIUM | V-1089 | AUDIT | The required legal notice must be configured to display before console logon."
  win_command: reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v LegalNoticeText
  register: legal_notice_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in legal_notice_audit.stderr and legal_notice_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1089

- name: "MEDIUM | V-1089 | PATCH | The required legal notice must be configured to display before console logon."
  win_regedit: 
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      value: "LegalNoticeText"
      data: "{{ legal_notice }}"
  tags:
      - cat2
      - medium
      - patch
      - V-1089

- name: "MEDIUM | V-1141 | AUDIT | Unencrypted passwords must not be sent to third-party SMB Servers."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters /v EnablePlainTextPassword
  register: plain_text_password_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in plain_text_password_audit.stderr and plain_text_password_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1141

- name: "MEDIUM | V-1141 | PATCH | Unencrypted passwords must not be sent to third-party SMB Servers."
  win_regedit: 
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters'
      value: EnablePlainTextPassword
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1141

- name: "MEDIUM | V-1154 | AUDIT | The Ctrl+Alt+Del security attention sequence for logons will be enabled."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v DisableCAD
  register: disable_CAD_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_CAD_audit.stderr and disable_CAD_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1154

- name: "MEDIUM | V-1154 | PATCH | The Ctrl+Alt+Del security attention sequence for logons will be enabled."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: DisableCAD
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1154

- name: "MEDIUM | V-1157 | AUDIT | The Smart Card removal option will be configured to Force Logoff or Lock Workstation."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v SCRemoveOption
  register: SC_removal_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in SC_removal_audit.stderr and SC_removal_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1157

- name: "MEDIUM | V-1157 | PATCH | The Smart Card removal option will be configured to Force Logoff or Lock Workstation."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: SCRemoveOption
      data: 1
  tags:
      - cat2
      - medium
      - patch
      - V-1157

- name: "MEDIUM | V-1162 | AUDIT | The Windows SMB server will perform SMB packet signing when possible."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v EnableSecuritySignature
  register: SMB_server_packet_signing_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in SMB_server_packet_signing_audit.stderr and SMB_server_packet_signing_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1162

- name: "MEDIUM | V-1162 | PATCH | The Windows SMB server will perform SMB packet signing when possible."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
      value: EnableSecuritySignature
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1162

- name: "MEDIUM | V-1163 | AUDIT | Outgoing secure channel traffic will be encrypted when possible."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Netlogon\Parameters /v SealSecureChannel
  register: encrypt_outgoing_secure_channel_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in encrypt_outgoing_secure_channel_audit.stderr and encrypt_outgoing_secure_channel_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1163

- name: "MEDIUM | V-1163 | PATCH | Outgoing secure channel traffic will be encrypted when possible."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: SealSecureChannel
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1163

- name: "MEDIUM | V-1164 | AUDIT | Outgoing secure channel traffic will be signed when possible."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Netlogon\Parameters /v SignSecureChannel
  register: sign_outgoing_secure_channel_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in sign_outgoing_secure_channel_audit.stderr and sign_outgoing_secure_channel_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1164

- name: "MEDIUM | V-1164 | PATCH | Outgoing secure channel traffic will be signed when possible."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: SignSecureChannel
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1164

- name: "MEDIUM | V-1166 | AUDIT | The Windows SMB client will be enabled to perform SMB packet signing when possible."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters /v EnableSecuritySignature
  register: SMB_client_packet_signing_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in SMB_client_packet_signing_audit.stderr and SMB_client_packet_signing_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1166

- name: "MEDIUM | V-1166 | PATCH | The Windows SMB client will be enabled to perform SMB packet signing when possible."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters'
      value: EnableSecuritySignature
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1166

- name: "MEDIUM | V-1171 | AUDIT | Ejection of removable NTFS media is not restricted to Administrators."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v AllocateDASD
  register: eject_removable_media_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in eject_removable_media_audit.stderr and eject_removable_media_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1171

- name: "MEDIUM | V-1171 | PATCH | Ejection of removable NTFS media is not restricted to Administrators."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: AllocateDASD
      data: 0
  tags:
      - cat2
      - medium
      - patch
      - V-1171

- name: "MEDIUM | V-3372 | AUDIT | A system must be logged on to before removing from a docking station."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v UndockWithoutLogon
  register: undock_logon_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in undock_logon_audit.stderr and undock_logon_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3372

- name: "MEDIUM | V-3372 | PATCH | A system must be logged on to before removing from a docking station."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: UndockWithoutLogon
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3372

- name: "MEDIUM | V-3376 | AUDIT | The system will be configured to prevent the storage of passwords and credentials"
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v DisableDomainCreds
  register: creds_storage_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in creds_storage_audit.stderr and creds_storage_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3376

- name: "MEDIUM | V-3376 | PATCH | The system will be configured to prevent the storage of passwords and credentials"
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: DisableDomainCreds
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3376

- name: "MEDIUM | V-3377 | AUDIT | The system will be configured to prevent anonymous users from having the same rights as the Everyone group."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v EveryoneIncludesAnonymous
  register: everyone_includes_anon_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in everyone_includes_anon_audit.stderr and everyone_includes_anon_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3377

- name: "MEDIUM | V-3377 | PATCH | The system will be configured to prevent anonymous users from having the same rights as the Everyone group."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: EveryoneIncludesAnonymous
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3377

- name: "MEDIUM | V-3378 | AUDIT | The system will be configured to use the Classic security model."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v ForceGuest
  register: classic_security_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in classic_security_audit.stderr and classic_security_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3378

- name: "MEDIUM | V-3378 | PATCH | The system will be configured to use the Classic security model."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: ForceGuest
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3378

- name: "MEDIUM | V-3381 | AUDIT | The system will be configured to the required LDAP client signing level."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LDAP /v LDAPClientIntegrity
  register: LDAP_client_integrity_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in LDAP_client_integrity_audit.stderr and LDAP_client_integrity_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3381

- name: "MEDIUM | V-3381 | PATCH | The system will be configured to the required LDAP client signing level."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\LDAP'
      value: LDAPClientIntegrity
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3381

- name: "MEDIUM | V-3382 | AUDIT | The system will be configured to meet the minimum session security requirement for NTLM SSP based clients."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa\MSV1_0 /v NTLMMinClientSec
  register: NTLM_min_client_sec_audit
  check_mode: no
  changed_when: "'0x20080000' not in NTLM_min_client_sec_audit.stdout"
  failed_when: "reg_not_found not in NTLM_min_client_sec_audit.stderr and NTLM_min_client_sec_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3382

# - name: "MEDIUM | V-3382 | PATCH | The system will be configured to meet the minimum session security requirement for NTLM SSP based clients."
#   win_command: true
#   tags:
#       - cat2
#       - medium
#       - patch
#       - V-3382

- name: "MEDIUM | V-3385 | AUDIT | The system must be configured to require case insensitivity for non-Windows subsystems."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\Session Manager\Kernel\" /v ObCaseInsensitive
  register: case_insensitive_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in case_insensitive_audit.stderr and case_insensitive_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3385

- name: "MEDIUM | V-3385 | PATCH | The system must be configured to require case insensitivity for non-Windows subsystems."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Session Manager\Kernel'
      value: ObCaseInsensitive
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3385

- name: "MEDIUM | V-3449 | AUDIT | Remote Desktop Services will limit users to one remote session."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v fSingleSessionPerUser
  register: single_rdp_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in single_rdp_audit.stderr and single_rdp_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3449

- name: "MEDIUM | V-3449 | PATCH | Remote Desktop Services will limit users to one remote session."
  win_regedit: 
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: fSingleSessionPerUser
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3449

- name: "MEDIUM | V-3453 | AUDIT | Remote Desktop Services will always prompt a client for passwords upon connection."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v fPromptForPassword
  register: rdp_password_prompt_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in rdp_password_prompt_audit.stderr and rdp_password_prompt_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3453

- name: "MEDIUM | V-3453 | PATCH | Remote Desktop Services will always prompt a client for passwords upon connection."
  win_regedit: 
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: fPromptForPassword
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3453

- name: "MEDIUM | V-3454 | AUDIT | Remote Desktop Services will be configured with the client connection encryption set to the required level."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v MinEncryptionLevel
  register: min_encrypt_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in min_encrypt_audit.stderr and min_encrypt_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3454

# - name: "MEDIUM | V-3454 | PATCH | Remote Desktop Services will be configured with the client connection encryption set to the required level."
#   win_command: true
#   tags:
#       - cat2
#       - medium
#       - patch
#       - V-3454

- name: "MEDIUM | V-3455 | AUDIT | Remote Desktop Services will be configured to use session-specific temporary folders."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v PerSessionTempDir
  register: temp_folder_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in temp_folder_audit.stderr and temp_folder_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3455

- name: "MEDIUM | V-3455 | PATCH | Remote Desktop Services will be configured to use session-specific temporary folders."
  win_regedit: 
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: PerSessionTempDir
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3455

- name: "MEDIUM | V-3456 | AUDIT | Remote Desktop Services will delete temporary folders when a session is terminated."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v DeleteTempDirsOnExit
  register: delete_temp_folder_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in delete_temp_folder_audit.stderr and delete_temp_folder_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-3456

- name: "MEDIUM | V-3456 | PATCH | Remote Desktop Services will delete temporary folders when a session is terminated."
  win_regedit: 
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: DeleteTempDirsOnExit
      data: 1
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-3456

