- name: "LOW | V-1075 | AUDIT | The shutdown option will not be available from the logon dialog box."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v ShutdownWithoutLogon
  register: shutdown_button_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1075

- name: "LOW | V-1075 | PATCH | The shutdown option will not be available from the logon dialog box."
  win_regedit: 
    key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
    value: ShutdownWithoutLogon
    data: 0
    datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1075

- name: "LOW | V-1090 | AUDIT | Caching of logon credentials must be limited."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v CachedLogonsCount
  register: cached_logons_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1090

- name: "LOW | V-1090 | PATCH | Caching of logon credentials must be limited."
  win_regedit: 
    key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
    value: CachedLogonsCount
    data: 2
  tags:
      - cat3
      - low
      - patch
      - V-1090

- name: "LOW | V-1136 | AUDIT | Users will be forcibly disconnected when their logon hours expire."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v EnableForcedLogoff
  register: forced_logoff_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1136

- name: "LOW | V-1136 | PATCH | Users will be forcibly disconnected when their logon hours expire."
  win_regedit: 
    key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
    value: EnableForcedLogoff
    data: 1
    datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1136

- name: "LOW | V-1151 | AUDIT | The print driver installation privilege will be restricted to administrators."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers\" /v AddPrinterDrivers
  register: add_printer_driver_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1151

- name: "LOW | V-1151 | PATCH | The print driver installation privilege will be restricted to administrators."
  win_regedit: 
    key: 'HKLM:\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers'
    value: AddPrinterDrivers
    data: 1
    datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1151

- name: "LOW | V-1158 | AUDIT | The Recovery Console SET command must be disabled."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SetCommand
  register: set_command_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1158

- name: "LOW | V-1158 | PATCH | The Recovery Console SET command must be disabled."
  win_regedit: 
    key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
    value: SetCommand
    data: 0
    datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1158

- name: "LOW | V-1165 | AUDIT | The computer account password will not be prevented from being reset."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Netlogon\Parameters /v DisablePasswordChange
  register: disable_password_change_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - audit
      - V-1165

- name: "LOW | V-1165 | PATCH | The computer account password will not be prevented from being reset."
  win_regedit: 
    key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
    value: DisablePasswordChange
    data: 0
    datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1165

