- name: "LOW | V-1075 | AUDIT | The shutdown option will not be available from the logon dialog box."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v ShutdownWithoutLogon
  register: shutdown_button_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in shutdown_button_audit.stderr and shutdown_button_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1075

- name: "LOW | V-1075 | PATCH | The shutdown option will not be available from the logon dialog box."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: ShutdownWithoutLogon
      data: 0
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1075

- name: "LOW | V-1090 | AUDIT | Caching of logon credentials must be limited."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v CachedLogonsCount
  register: cached_logons_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in cached_logons_audit.stderr and cached_logons_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1090

- name: "LOW | V-1090 | PATCH | Caching of logon credentials must be limited."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: CachedLogonsCount
      data: 0
  tags:
      - cat3
      - low
      - patch
      - V-1090

# - name: "LOW | V-1136 | AUDIT | Users will be forcibly disconnected when their logon hours expire."
#   win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v EnableForcedLogoff
#   register: forced_logoff_audit
#   check_mode: no
#   changed_when: no
#   failed_when: "reg_not_found not in forced_logoff_audit.stderr and forced_logoff_audit.stderr"
#   tags:
#       - cat3
#       - low
#       - audit
#       - V-1136

# - name: "LOW | V-1136 | PATCH | Users will be forcibly disconnected when their logon hours expire."
#   win_regedit: 
#       key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
#       value: EnableForcedLogoff
#       data: 1
#       datatype: dword
#   tags:
#       - cat3
#       - low
#       - patch
#       - V-1136

- name: "LOW | V-1151 | AUDIT | The print driver installation privilege will be restricted to administrators."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers\" /v AddPrinterDrivers
  register: add_printer_driver_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in add_printer_driver_audit.stderr and add_printer_driver_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1151

- name: "LOW | V-1151 | PATCH | The print driver installation privilege will be restricted to administrators."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers'
      value: AddPrinterDrivers
      data: 1
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1151

- name: "LOW | V-1158 | AUDIT | The Recovery Console SET command must be disabled."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SetCommand
  register: set_command_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in set_command_audit.stderr and set_command_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1158

- name: "LOW | V-1158 | PATCH | The Recovery Console SET command must be disabled."
  win_regedit: 
      key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
      value: SetCommand
      data: 0
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1158

- name: "LOW | V-1165 | AUDIT | The computer account password will not be prevented from being reset."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Netlogon\Parameters /v DisablePasswordChange
  register: disable_password_change_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_password_change_audit.stderr and disable_password_change_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1165

- name: "LOW | V-1165 | PATCH | The computer account password will not be prevented from being reset."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: DisablePasswordChange
      data: 0
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1165

- name: "LOW | V-1172 | AUDIT | Users will be warned in advance that their passwords will expire."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v PasswordExpiryWarning
  register: password_expiry_warning_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in password_expiry_warning_audit.stderr and password_expiry_warning_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1172

- name: "LOW | V-1172 | PATCH | Users will be warned in advance that their passwords will expire."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: PasswordExpiryWarning
      data: 7
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1172

- name: "LOW | V-1173 | AUDIT | The default permissions of Global system objects will be increased."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\Session Manager\" /v ProtectionMode
  register: protection_mode_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in protection_mode_audit.stderr and protection_mode_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1173

- name: "LOW | V-1173 | PATCH | The default permissions of Global system objects will be increased."
  win_regedit: 
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: ProtectionMode
      data: 1
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1173

- name: "LOW | V-1174 | AUDIT | The amount of idle time required before suspending a session must be properly set."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters /v autodisconnect
  register: auto_disconnect_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in auto_disconnect_audit.stderr and auto_disconnect_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-1174

- name: "LOW | V-1174 | PATCH | The amount of idle time required before suspending a session must be properly set."
  win_regedit: 
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters'
      value: autodisconnect
      data: 0x0000000f
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-1174

- name: "LOW | V-3373 | AUDIT | The maximum age for machine account passwords will be set to requirements."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Netlogon\Parameters /v MaximumPasswordAge
  register: max_password_age_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in max_password_age_audit.stderr and max_password_age_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-3373

- name: "LOW | V-3373 | PATCH | The maximum age for machine account passwords will be set to requirements."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: MaximumPasswordAge
      data: 30
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-3373

- name: "LOW | V-4110 | AUDIT | The system will be configured to prevent IP source routing."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters /v DisableIPSourceRouting
  register: disable_ip_routing_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_ip_routing_audit.stderr and disable_ip_routing_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4110

- name: "LOW | V-4110 | PATCH | The system will be configured to prevent IP source routing."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-4110

- name: "LOW | V-4111 | AUDIT | The system will be configured to prevent ICMP redirects from overriding OSPF generated routes."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters /v EnableICMPRedirect
  register: enable_ICMP_routing_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in enable_ICMP_routing_audit.stderr and enable_ICMP_routing_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4111

- name: "LOW | V-4111 | PATCH | The system will be configured to prevent ICMP redirects from overriding OSPF generated routes."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: EnableICMPRedirect
      data: 0
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-4111

- name: "LOW | V-4112 | AUDIT | The system will be configured to disable the Internet Router Discover Protocol (IRDP)."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters /v PerformRouterDiscovery
  register: disable_IRDP_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in disable_IRDP_audit.stderr and disable_IRDP_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4112

- name: "LOW | V-4112 | PATCH | The system will be configured to disable the Internet Router Discover Protocol (IRDP)."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: PerformRouterDiscovery
      data: 0
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-4112

- name: "LOW | V-4113 | AUDIT | The system will be configured to limit how often keep-alive packets are sent."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters /v KeepAliveTime
  register: keep_alive_time_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in keep_alive_time_audit.stderr and keep_alive_time_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4113

- name: "LOW | V-4113 | PATCH | The system will be configured to limit how often keep-alive packets are sent."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: KeepAliveTime
      data: 300000
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-4113

- name: "LOW | V-4438 | AUDIT | The system must limit how many times unacknowledged TCP data is retransmitted."
  win_command: reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters /v TcpMaxDataRetransmissions
  register: max_TCP_retransmit_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in max_TCP_retransmit_audit.stderr and max_TCP_retransmit_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4438

- name: "LOW | V-4438 | PATCH | The system must limit how many times unacknowledged TCP data is retransmitted."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: TcpMaxDataRetransmissions
      data: 3
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-4438

- name: "LOW | V-4442 | AUDIT | The system will be configured to have password protection take effect within a limited time frame when the screen saver becomes active."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v ScreenSaverGracePeriod
  register: screen_saver_password_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in screen_saver_password_audit.stderr and screen_saver_password_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4442

- name: "LOW | V-4442 | PATCH | The system will be configured to have password protection take effect within a limited time frame when the screen saver becomes active."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: ScreenSaverGracePeriod
      data: 0
  tags:
      - cat3
      - low
      - patch
      - V-4442

- name: "LOW | V-4445 | AUDIT | Optional Subsystems will not be permitted to operate on the system."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\Session Manager\Subsystems\" /v Optional
  register: optional_subsystem_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in optional_subsystem_audit.stderr and optional_subsystem_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-4445

- name: "LOW | V-4445 | PATCH | Optional Subsystems will not be permitted to operate on the system."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Session Manager\Subsystems'
      value: Optional
      data: ''
      datatype: multistring
  tags:
      - cat3
      - low
      - patch
      - V-4445

- name: "LOW | V-11806 | AUDIT | The system will be configured to prevent the display of the last user name on the logon screen."
  win_command: reg query \"HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System\" /v DontDisplayLastUserName
  register: last_name_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in last_name_audit.stderr and last_name_audit.stderr"
  tags:
      - cat3
      - low
      - audit
      - V-11806

- name: "LOW | V-11806 | PATCH | The system will be configured to prevent the display of the last user name on the logon screen."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: DontDisplayLastUserName
      data: 1
      datatype: dword
  tags:
      - cat3
      - low
      - patch
      - V-11806

